twist_mux:
  ros__parameters:
    use_sim_time: false
    topics:
      nav2:
        topic: /cmd_vel_nav
        timeout: 0.5
        priority: 50
      joystick:
        topic: /cmd_vel_joy
        timeout: 0.5
        priority: 90
      keyboard:
        topic: /cmd_vel_teleop
        timeout: 0.5
        priority: 100
